# Generated by Django 4.2.26 on 2025-11-26 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rocznik', models.IntegerField()),
                ('pojemnosc_silnika', models.CharField(max_length=50)),
                ('moc', models.IntegerField()),
                ('przyspieszenie', models.CharField(max_length=50)),
                ('predkosc_maksymalna', models.IntegerField()),
                ('skrzynia_biegow', models.CharField(choices=[('manualna', 'Manualna'), ('automatyczna', 'Automatyczna')], max_length=20)),
                ('liczba_miejsc', models.IntegerField()),
                ('naped', models.CharField(choices=[('rwd', 'RWD'), ('awd', 'AWD'), ('fwd', 'FWD')], max_length=10)),
                ('cena_za_dobe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('dostepny', 'Dostępny'), ('niedostepny', 'Niedostępny')], default='dostepny', max_length=20)),
                ('kod_samochodu', models.CharField(editable=False, max_length=50, unique=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='samochody/')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('klient', 'Klient'), ('pracownik', 'Pracownik'), ('admin', 'Administrator')], default='klient', max_length=20)),
                ('kod_uzytkownika', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odbioru', models.DateTimeField()),
                ('data_zwrotu', models.DateTimeField()),
                ('miejsce_odbioru', models.CharField(max_length=200)),
                ('miejsce_zwrotu', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('potwierdzony', 'Potwierdzony'), ('zakonczony', 'Zakończony'), ('anulowany', 'Anulowany')], default='oczekujacy', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('kod_rezerwacji', models.CharField(editable=False, max_length=50, unique=True)),
                ('kwota_razem', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje_klient', to=settings.AUTH_USER_MODEL)),
                ('pracownik_potwierdzajacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rezerwacje_potwierdzone', to=settings.AUTH_USER_MODEL)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='rentar_app.samochod')),
            ],
        ),
    ]
