# Generated by Django 4.2.26 on 2025-11-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='imie_klienta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='nazwisko_klienta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
